import type { Metadata } from "next";
import { Markazi_Text } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { SpeedInsights } from "@vercel/speed-insights/next";

const markazi = Markazi_Text({ subsets: ["latin", "arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../assets/images/favicon.ico" sizes="any" />
      </head>
      <body className={markazi.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
