import type { Metadata } from "next";
import { Markazi_Text } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { SpeedInsights } from "@vercel/speed-insights/next";

const markazi = Markazi_Text({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Saleh Niknejad",
  description: "Generated by salehNiknejad",
  // icons:
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={markazi.className}>
        <AntdRegistry>{children}</AntdRegistry>
        <SpeedInsights />
      </body>
    </html>
  );
}
